In [2]:
path = 'examples/segismundo.txt'

f = open(path)

In [3]:
lines = [x.rstrip() for x in open(path)]
lines

['Sueña el rico en su riqueza,',
 'que más cuidados le ofrece;',
 '',
 'sueña el pobre que padece',
 'su miseria y su pobreza;',
 '',
 'sueña el que a medrar empieza,',
 'sueña el que afana y pretende,',
 'sueña el que agravia y ofende,',
 '',
 'y en el mundo, en conclusión,',
 'todos sueñan lo que son,',
 'aunque ninguno lo entiende.']

In [4]:
f.close()

with open(path) as f:
    lines = [x.rstrip() for x in f]

In [5]:
f = open(path)
f.read(10)

'Sueña el r'

In [6]:
f2 = open(path , 'rb') # Binary mode
f2.read(10)

b'Sue\xf1a el r'

In [7]:
f.tell()

10

In [8]:
f2.tell()

10

In [9]:
import sys

sys.getdefaultencoding()

'utf-8'

In [10]:
f.seek(3)

3

In [11]:
f.read(1)

'ñ'

In [12]:
f.close()
f2.close()

In [15]:
with open('tmp.txt', 'w') as handle:
    handle.writelines(x for x in open(path) if len(x) > 1)

with open('tmp.txt') as f:
    lines = f.readlines()
    
lines

['Sueña el rico en su riqueza,\n',
 'que más cuidados le ofrece;\n',
 'sueña el pobre que padece\n',
 'su miseria y su pobreza;\n',
 'sueña el que a medrar empieza,\n',
 'sueña el que afana y pretende,\n',
 'sueña el que agravia y ofende,\n',
 'y en el mundo, en conclusión,\n',
 'todos sueñan lo que son,\n',
 'aunque ninguno lo entiende.\n']

In [16]:
# Introducción a Numpy

import numpy as np

In [17]:
my_arr = np.arange(1000000)

In [18]:
my_list = list(range(1000000))

In [19]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 28.9 ms


In [20]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 1.13 s


In [21]:
# Generate some random data

data = np.random.randn(2, 3)

data

array([[-0.29275567, -0.60070699,  0.54799163],
       [-1.45709067,  1.47602005,  0.71636006]])

In [22]:
data * 10

array([[ -2.92755666,  -6.00706987,   5.47991634],
       [-14.57090669,  14.76020049,   7.1636006 ]])

In [23]:
data + data

array([[-0.58551133, -1.20141397,  1.09598327],
       [-2.91418134,  2.9520401 ,  1.43272012]])

In [24]:
data.shape

(2, 3)

In [25]:
data.dtype

dtype('float64')

In [26]:
data1 = [6, 7.5, 8, 0, 1]

arr1 = np.array(data1)

arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [27]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

arr2 = np.array(data2)

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [28]:
arr2.ndim

2

In [29]:
arr2.shape

(2, 4)

In [30]:
arr1.dtype

dtype('float64')

In [31]:
arr2.dtype

dtype('int32')

In [32]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [34]:
np.empty((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [35]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [36]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

arr2 = np.array([1, 2, 3], dtype=np.int32)

arr1.dtype

dtype('float64')

In [37]:
arr2.dtype

dtype('int32')

In [38]:
arr = np.array([1, 2, 3, 4, 5])

arr.dtype

dtype('int32')

In [39]:
float_arr = arr.astype(np.float64)

float_arr.dtype

dtype('float64')

In [40]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [41]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [42]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [43]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [44]:
int_array = np.arange(10)

calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])