In [1]:
import numpy as np
import pandas as pd

from pandas import DataFrame, Series

In [2]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                     'k2': [1, 1, 2, 3, 3, 4, 4]})

In [3]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [4]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [5]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [6]:
data['v1'] = range(7)

In [7]:
data.drop_duplicates('k1')

k1  k2  v1
0  one   1   0
1  two   1   1

In [8]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [9]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
                              'Pastrami', 'corned beef', 'Bacon',
                              'pastrami', 'honey ham', 'nova lox'],
                     'ounces': [4, 3, 12, 6, 7.5, 8, 3 , 5, 6]})

In [10]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [12]:
meat_to_animal = {
    'bacon': 'pig',
    'pulled pork': 'pig',
    'pastrami': 'cow',
    'corned beef': 'cow',
    'honey ham': 'pig',
    'nova lox': 'salmon'
}

In [13]:
lowercased = data['food'].str.lower()

In [14]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [15]:
data['animal'] = lowercased.map(meat_to_animal)

In [16]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [17]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [18]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [19]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [20]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [21]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [22]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [23]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [25]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [26]:
transform = lambda x: x[:4].upper()

In [27]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [28]:
data.index = data.index.map(transform)

In [29]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [30]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [31]:
data.rename(index={'OHIO': 'INDIANA'},
            columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [32]:
data.rename(index= {'OHIO': 'INDIANA'},
            columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [35]:
data.rename(index= {'OHIO': 'INDIANA'}, inplace=True)

In [36]:
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

In [37]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [38]:
bins = [18, 25, 35, 60, 100]

In [39]:
cats = pd.cut(ages, bins)

In [40]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [41]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [42]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [43]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [44]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [45]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

In [46]:
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [47]:
data = np.random.randn(20)

In [48]:
pd.cut(data, 4, precision=2)

[(0.96, 1.92], (-0.012, 0.96], (-1.95, -0.98], (-1.95, -0.98], (-0.012, 0.96], ..., (0.96, 1.92], (-0.012, 0.96], (-0.98, -0.012], (-1.95, -0.98], (0.96, 1.92]]
Length: 20
Categories (4, interval[float64]): [(-1.95, -0.98] < (-0.98, -0.012] < (-0.012, 0.96] < (0.96, 1.92]]

In [49]:
data = np.random.randn(1000) # Normally distributed

In [50]:
cats = pd.qcut(data, 4) # Cut into quartiles

In [51]:
cats

[(-0.776, -0.0732], (-3.062, -0.776], (-0.776, -0.0732], (-0.776, -0.0732], (-0.776, -0.0732], ..., (-3.062, -0.776], (0.61, 2.867], (-0.776, -0.0732], (-0.776, -0.0732], (0.61, 2.867]]
Length: 1000
Categories (4, interval[float64]): [(-3.062, -0.776] < (-0.776, -0.0732] < (-0.0732, 0.61] < (0.61, 2.867]]

In [52]:
pd.value_counts(cats)

(0.61, 2.867]        250
(-0.0732, 0.61]      250
(-0.776, -0.0732]    250
(-3.062, -0.776]     250
dtype: int64

In [53]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(-1.42, -0.0732], (-3.062, -1.42], (-1.42, -0.0732], (-1.42, -0.0732], (-1.42, -0.0732], ..., (-3.062, -1.42], (1.197, 2.867], (-1.42, -0.0732], (-1.42, -0.0732], (-0.0732, 1.197]]
Length: 1000
Categories (4, interval[float64]): [(-3.062, -1.42] < (-1.42, -0.0732] < (-0.0732, 1.197] < (1.197, 2.867]]

In [54]:
data = pd.DataFrame(np.random.randn(1000, 4))

In [55]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.016163    -0.016681     0.050437     0.009532
std       1.007244     0.999537     1.000519     1.015421
min      -4.671955    -3.200856    -3.098930    -2.904849
25%      -0.661414    -0.694226    -0.525376    -0.700748
50%       0.035951     0.001913     0.063880     0.031084
75%       0.660703     0.658447     0.674273     0.678569
max       2.832237     3.549474     3.634620     3.308016

In [56]:
col = data[2]

In [57]:
col[np.abs(col) > 3]

26     3.161112
432    3.002222
554    3.185075
649    3.634620
773   -3.098930
Name: 2, dtype: float64

In [58]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
26  -1.786550  0.578309  3.161112  1.158835
68   2.802917 -2.610868  0.197791  3.308016
169  0.918151  3.463312 -0.423786  0.056135
432  0.156851  0.280016  3.002222  1.600271
483 -0.346675  0.834040 -0.501419  3.150036
493 -4.671955  0.384480 -1.750180 -0.166367
509 -0.888432  3.549474  1.354451  0.329461
536  1.314630  3.027712  0.987139 -0.797615
554 -0.988588  0.246584  3.185075 -1.400113
649  0.344714  0.079673  3.634620  1.593782
773  0.078029  2.111384 -3.098930  0.992852
911 -3.120536 -0.588300  0.885815 -0.427568
915 -3.146571  0.314085  0.919759  0.070874
944  0.186055 -3.200856  0.431302 -0.402557

In [59]:
data[np.abs(data) > 3] = np.sign(data) * 3

In [60]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.018102    -0.017520     0.049553     0.009074
std       0.999997     0.995506     0.997073     1.014011
min      -3.000000    -3.000000    -3.000000    -2.904849
25%      -0.661414    -0.694226    -0.525376    -0.700748
50%       0.035951     0.001913     0.063880     0.031084
75%       0.660703     0.658447     0.674273     0.678569
max       2.832237     3.000000     3.000000     3.000000

In [61]:
np.sign(data).head()

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0 -1.0 -1.0  1.0
2 -1.0  1.0  1.0 -1.0
3 -1.0 -1.0 -1.0  1.0
4  1.0 -1.0 -1.0 -1.0

In [62]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))

In [63]:
sampler = np.random.permutation(5)

In [64]:
sampler

array([1, 4, 3, 0, 2])

In [65]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [66]:
df.take(sampler)

0   1   2   3
1   4   5   6   7
4  16  17  18  19
3  12  13  14  15
0   0   1   2   3
2   8   9  10  11

In [67]:
df.sample(n=3)

0   1   2   3
2   8   9  10  11
0   0   1   2   3
4  16  17  18  19

In [68]:
choices = pd.Series([5, 7, -1, 6, 4])

In [70]:
draws = choices.sample(n=10, replace=True)

In [71]:
draws

4    4
4    4
2   -1
3    6
2   -1
1    7
3    6
1    7
4    4
1    7
dtype: int64

In [72]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                   'data1': range(6)})

In [73]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [74]:
dummies = pd.get_dummies(df['key'], prefix='key')

In [75]:
df_with_dummy = df[['data1']].join(dummies)

In [76]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [77]:
mnames = ['movie_id', 'title', 'genres']

In [81]:
movies = pd.read_table('datasets/movielens/movies.dat', sep='::',
                         header=None, names=mnames)

C:\Users\mo0amil\Miniconda3\lib\site-packages\ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  


In [82]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [83]:
all_genres = []

In [84]:
for x in movies.genres:
    all_genres.extend(x.split('|'))

In [85]:
genres = pd.unique(all_genres)

In [86]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [87]:
zero_matrix = np.zeros((len(movies), len(genres)))

In [88]:
dummies = pd.DataFrame(zero_matrix, columns=genres)

In [89]:
gen = movies.genres[0]

In [90]:
gen.split('|')

['Animation', "Children's", 'Comedy']

In [92]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2], dtype=int64)

In [94]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices] = 1

In [95]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))

In [96]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Adventure                                0
Genre_Fantasy                                  0
Genre_Romance                                  0
Genre_Drama                                    0
Genre_Action                                   0
Genre_Crime                                    0
Genre_Thriller                                 0
Genre_Horror                                   0
Genre_Sci-Fi                                   0
Genre_Documentary                              0
Genre_War                                      0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Film-Noir                                0
Genre_Western       

In [97]:
np.random.seed(12345)

In [98]:
values = np.random.rand(10)

In [99]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [100]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [101]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0